# Generated by Django 3.0.5 on 2020-04-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='feature',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
